name: Build and configure

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - name: lint
      run: npm run lint
    - name: build
      run: npx webpack --mode=production
      env:
        PUBLIC_PATH: '/AncientBeast/'
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: deploy
        path: deploy
      
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - name: run tests
      run: npm test

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: deploy
      # Uses: https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
